// export const API_URL = 'https://find-document-backend.onrender.com/api/'
export const API_URL = 'https://product-booker.onrender.com/api/'

export const LOGIN = API_URL + 'user/login'
export const PRODUCTS = API_URL + 'products'
export const POST_PRODUCTS = API_URL + 'products'
export const GET_CATEGORIES = PRODUCTS + '/categories'
export const USERS = API_URL + 'user'
export const POST_USERS = API_URL + 'user'
export const POST_COMMANDS = API_URL + 'commande'
export const GET_COMMANDS = API_URL + 'commande'
export const PUT_COMMANDS = API_URL + 'commande/'
export const HIDE_PRODUCT = PRODUCTS + '/delete-produit/'
export const SHOW_PRODUCT = PRODUCTS + '/activate-produit/'
export const PUT_PRODUCT = API_URL + 'produit/'
export const UPDATE_COMMAND = POST_COMMANDS + '/update-commande/'
